/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.movies.avroDto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MovieKafkaDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3794301897168898660L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MovieDto\",\"namespace\":\"com.example.movies.avroDto\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"movieId\",\"type\":\"string\"},{\"name\":\"movieName\",\"type\":\"string\"},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MovieKafkaDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MovieKafkaDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MovieKafkaDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MovieKafkaDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MovieKafkaDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MovieDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MovieDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MovieDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MovieKafkaDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence movieId;
  private java.lang.CharSequence movieName;
  private java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MovieKafkaDto() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param movieId The new value for movieId
   * @param movieName The new value for movieName
   * @param description The new value for description
   */
  public MovieKafkaDto(java.lang.Long id, java.lang.CharSequence movieId, java.lang.CharSequence movieName, java.lang.CharSequence description) {
    this.id = id;
    this.movieId = movieId;
    this.movieName = movieName;
    this.description = description;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return movieId;
    case 2: return movieName;
    case 3: return description;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: movieId = (java.lang.CharSequence)value$; break;
    case 2: movieName = (java.lang.CharSequence)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'movieId' field.
   * @return The value of the 'movieId' field.
   */
  public java.lang.CharSequence getMovieId() {
    return movieId;
  }


  /**
   * Sets the value of the 'movieId' field.
   * @param value the value to set.
   */
  public void setMovieId(java.lang.CharSequence value) {
    this.movieId = value;
  }

  /**
   * Gets the value of the 'movieName' field.
   * @return The value of the 'movieName' field.
   */
  public java.lang.CharSequence getMovieName() {
    return movieName;
  }


  /**
   * Sets the value of the 'movieName' field.
   * @param value the value to set.
   */
  public void setMovieName(java.lang.CharSequence value) {
    this.movieName = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Creates a new MovieDto RecordBuilder.
   * @return A new MovieDto RecordBuilder
   */
  public static com.example.movies.avroDto.MovieKafkaDto.Builder newBuilder() {
    return new com.example.movies.avroDto.MovieKafkaDto.Builder();
  }

  /**
   * Creates a new MovieDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MovieDto RecordBuilder
   */
  public static com.example.movies.avroDto.MovieKafkaDto.Builder newBuilder(com.example.movies.avroDto.MovieKafkaDto.Builder other) {
    if (other == null) {
      return new com.example.movies.avroDto.MovieKafkaDto.Builder();
    } else {
      return new com.example.movies.avroDto.MovieKafkaDto.Builder(other);
    }
  }

  /**
   * Creates a new MovieDto RecordBuilder by copying an existing MovieDto instance.
   * @param other The existing instance to copy.
   * @return A new MovieDto RecordBuilder
   */
  public static com.example.movies.avroDto.MovieKafkaDto.Builder newBuilder(com.example.movies.avroDto.MovieKafkaDto other) {
    if (other == null) {
      return new com.example.movies.avroDto.MovieKafkaDto.Builder();
    } else {
      return new com.example.movies.avroDto.MovieKafkaDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for MovieDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MovieKafkaDto>
    implements org.apache.avro.data.RecordBuilder<MovieKafkaDto> {

    private long id;
    private java.lang.CharSequence movieId;
    private java.lang.CharSequence movieName;
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.movies.avroDto.MovieKafkaDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.movieId)) {
        this.movieId = data().deepCopy(fields()[1].schema(), other.movieId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.movieName)) {
        this.movieName = data().deepCopy(fields()[2].schema(), other.movieName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing MovieDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.movies.avroDto.MovieKafkaDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.movieId)) {
        this.movieId = data().deepCopy(fields()[1].schema(), other.movieId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.movieName)) {
        this.movieName = data().deepCopy(fields()[2].schema(), other.movieName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'movieId' field.
      * @return The value.
      */
    public java.lang.CharSequence getMovieId() {
      return movieId;
    }


    /**
      * Sets the value of the 'movieId' field.
      * @param value The value of 'movieId'.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder setMovieId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.movieId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'movieId' field has been set.
      * @return True if the 'movieId' field has been set, false otherwise.
      */
    public boolean hasMovieId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'movieId' field.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder clearMovieId() {
      movieId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'movieName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMovieName() {
      return movieName;
    }


    /**
      * Sets the value of the 'movieName' field.
      * @param value The value of 'movieName'.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder setMovieName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.movieName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'movieName' field has been set.
      * @return True if the 'movieName' field has been set, false otherwise.
      */
    public boolean hasMovieName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'movieName' field.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder clearMovieName() {
      movieName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.example.movies.avroDto.MovieKafkaDto.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MovieKafkaDto build() {
      try {
        MovieKafkaDto record = new MovieKafkaDto();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.movieId = fieldSetFlags()[1] ? this.movieId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.movieName = fieldSetFlags()[2] ? this.movieName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MovieKafkaDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<MovieKafkaDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MovieKafkaDto>
    READER$ = (org.apache.avro.io.DatumReader<MovieKafkaDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.movieId);

    out.writeString(this.movieName);

    if (this.description == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.description);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.movieId = in.readString(this.movieId instanceof Utf8 ? (Utf8)this.movieId : null);

      this.movieName = in.readString(this.movieName instanceof Utf8 ? (Utf8)this.movieName : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.description = null;
      } else {
        this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.movieId = in.readString(this.movieId instanceof Utf8 ? (Utf8)this.movieId : null);
          break;

        case 2:
          this.movieName = in.readString(this.movieName instanceof Utf8 ? (Utf8)this.movieName : null);
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.description = null;
          } else {
            this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










